name: reactive_dropdown_menu
description: Wrapper around dropdown_menu to use with reactive_forms.
version: 1.0.0
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_dropdown_menu
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.0.0
  reactive_forms: ">=19.0.0 <20.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
